version: '3.1'
services:
  db:
    image: mariadb:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: casacor
      MARIADB_USER: casacor
      MARIADB_PASSWORD: casacor
      MARIADB_ROOT_PASSWORD: casacor+
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    links:
      - db
volumes:
    mysql-data: