services:
  db:
    image: mariadb:latest
    container_name: casacor-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: casacor
      MARIADB_USER: casacor
      MARIADB_PASSWORD: casacor
      MARIADB_ROOT_PASSWORD: casacor+
    volumes:
      - ../storage/casacor_mysql:/var/lib/mysql
  app:
    container_name: casacor-apache
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8003:80
    volumes:
      - ./app:/var/www/html
    links:
      - db
volumes:
  mysql-data: